### ISSUE TITLE
Abnormally high error rate (over 90%)

### ISSUE THREAD

**Issue by jun-yeong-heo** [danielchang2002/TaxiBGC_2022#1]
After I run TaxiBGC, error rate is abnormally high. (over 90%)

First I was input the result of [KneadData](https://github.com/biobakery/kneaddata), an error rate of over 90% was obtained.
So I re-entered the unhandled raw-fastq files, but the error rate was still over 90%.

I don't know which one is the cause of problem. Can you help me to get TaxiBGC running normally?

I used whole genome shotgun seq data from human fecal sample and I installed TaxiBGC using conda by following the guide.
I attach the running log and output files. (input is raw-fastq files)

Thank you.

[stool_SG_001.log](https://github.com/danielchang2002/TaxiBGC_2022/files/10301836/stool_SG_001.log)
[stool_SG_001_BGC_FINAL_RESULT.txt](https://github.com/danielchang2002/TaxiBGC_2022/files/10301839/stool_SG_001_BGC_FINAL_RESULT.txt)
[stool_SG_001_BGC_metsp.txt](https://github.com/danielchang2002/TaxiBGC_2022/files/10301840/stool_SG_001_BGC_metsp.txt)
[stool_SG_001_covstats_taxibgc2022.txt](https://github.com/danielchang2002/TaxiBGC_2022/files/10301842/stool_SG_001_covstats_taxibgc2022.txt)

**Comment by danielchang2002** [comment]
Hi Jun-yeong,

TaxiBGC uses [BBmap](https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/bbmap-guide/) to align reads to the [MIBiG database](https://mibig.secondarymetabolites.org/).

The error rate that you see in the TaxiBGC output is from this read alignment step by BBMap. A high error rate may be due to sequencing issues of your sample, and should not due to an installation issue of TaxiBGC. It also makes sense that TaxiBGC is not detecting any BGCs in your sample if the error rate is so high.

To verify that your installation is working as expected, I would try to run TaxiBGC on the example metagenome sample following the tutorial [here](https://github.com/danielchang2002/TaxiBGC_2022/tree/main/example).

Let me know if you have any more issues!

-Daniel
